//! CLI integration tests on the tiny committed fixtures (tests/fixtures/tiny, generated by
//! `scripts/make_fixtures.py --layers 1 --embd 16 --vocab 37 --positions 8 --hf-shard 4KB`
//! with 4 gloo ranks). No Python needed to run these.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn fix(p: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/tiny")
        .join(p)
}

fn ckpt(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_ckpt"))
        .args(args)
        .output()
        .expect("run ckpt")
}

fn ok(args: &[&str]) -> String {
    let o = ckpt(args);
    assert!(
        o.status.success(),
        "ckpt {args:?} failed:\n{}\n{}",
        String::from_utf8_lossy(&o.stdout),
        String::from_utf8_lossy(&o.stderr)
    );
    String::from_utf8_lossy(&o.stdout).to_string()
}

fn s(p: &Path) -> &str {
    p.to_str().unwrap()
}

#[test]
fn inspect_all_formats() {
    for (p, fmt) in [
        ("dcp_fsdp", "pytorch-dcp"),
        ("dcp_fsdp_st", "pytorch-dcp"),
        ("dcp_2d", "pytorch-dcp"),
        ("hf_sharded", "hf-sharded-safetensors"),
        ("reference/model.safetensors", "safetensors"),
    ] {
        let j: serde_json::Value =
            serde_json::from_str(&ok(&["inspect", "--json", s(&fix(p))])).unwrap();
        assert_eq!(j["format"], fmt, "{p}");
    }
    let j: serde_json::Value =
        serde_json::from_str(&ok(&["inspect", "--json", s(&fix("dcp_fsdp"))])).unwrap();
    assert_eq!(j["non_tensor_items"]["optim.param_groups.0.lr"], 0.01);
}

#[test]
fn dcp_to_safetensors_matches_reference() {
    let td = tempfile::tempdir().unwrap();
    let out = td.path().join("m.safetensors");
    ok(&[
        "convert",
        s(&fix("dcp_fsdp")),
        "-o",
        s(&out),
        "--include",
        "model.*",
        "--strip-prefix",
        "model.",
    ]);
    let d = ok(&["diff", s(&out), s(&fix("reference/model.safetensors"))]);
    assert!(d.contains("RESULT: EQUAL"), "{d}");
    // the 2-D (Shard(0), Shard(1)) bf16 checkpoint and the safetensors-serialized DCP
    let d = ok(&[
        "diff",
        s(&fix("dcp_2d")),
        s(&fix("reference_2d/model.safetensors")),
    ]);
    assert!(d.contains("RESULT: EQUAL"));
    let d = ok(&[
        "diff",
        s(&fix("dcp_fsdp_st")),
        s(&fix("reference/model.safetensors")),
        "--strip-prefix-a",
        "model.",
    ]);
    assert!(d.contains("RESULT: EQUAL"));
    let d = ok(&[
        "diff",
        s(&fix("dcp_fsdp")),
        s(&fix("reference_optim/optim.safetensors")),
        "--include",
        "optim.*",
    ]);
    assert!(d.contains("RESULT: EQUAL"));
}

#[test]
fn reshard_and_dcp_roundtrip() {
    let td = tempfile::tempdir().unwrap();
    let r3 = td.path().join("r3");
    ok(&[
        "reshard",
        s(&fix("hf_sharded")),
        "-o",
        s(&r3),
        "--num-shards",
        "3",
    ]);
    assert!(r3.join("model.safetensors.index.json").exists());
    assert!(r3.join("model-00003-of-00003.safetensors").exists());
    assert!(
        ok(&["diff", s(&r3), s(&fix("reference/model.safetensors"))]).contains("RESULT: EQUAL")
    );
    let dcp = td.path().join("dcp");
    ok(&[
        "convert",
        s(&r3),
        "--to",
        "dcp",
        "--dcp-ranks",
        "2",
        "-o",
        s(&dcp),
    ]);
    assert!(
        ok(&["diff", s(&dcp), s(&fix("reference/model.safetensors"))]).contains("RESULT: EQUAL")
    );
}

#[test]
fn tp_split_merge() {
    let td = tempfile::tempdir().unwrap();
    let rules = Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/gpt2_tp_rules.yaml");
    let tp = td.path().join("tp2");
    ok(&[
        "reshard",
        s(&fix("hf_sharded")),
        "--tp",
        "2",
        "--rules",
        s(&rules),
        "-o",
        s(&tp),
    ]);
    let merged = td.path().join("merged.safetensors");
    ok(&["reshard", s(&tp), "-o", s(&merged)]);
    assert!(
        ok(&["diff", s(&merged), s(&fix("reference/model.safetensors"))]).contains("RESULT: EQUAL")
    );
}

#[test]
fn diff_exit_codes() {
    let o = ckpt(&[
        "diff",
        s(&fix("reference/model.safetensors")),
        s(&fix("reference_2d/model.safetensors")),
    ]);
    assert_eq!(o.status.code(), Some(1));
    let o = ckpt(&["inspect", "/nonexistent/path"]);
    assert_eq!(o.status.code(), Some(2));
}

#[test]
fn malicious_metadata_refused() {
    let td = tempfile::tempdir().unwrap();
    // pickle.dumps(obj) where obj.__reduce__ = (os.system, ('touch pwned',)), protocol 2
    let evil = b"\x80\x02cposix\nsystem\nq\x00X\x0b\x00\x00\x00touch pwnedq\x01\x85q\x02Rq\x03.";
    std::fs::write(td.path().join(".metadata"), evil).unwrap();
    let o = ckpt(&["inspect", s(td.path())]);
    assert_eq!(o.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&o.stderr).contains("refusing pickle global `posix.system`"));
}

fn ckpt_env(args: &[&str], env: &[(&str, &str)]) -> Output {
    let mut c = Command::new(env!("CARGO_BIN_EXE_ckpt"));
    c.args(args);
    for (k, v) in env {
        c.env(k, v);
    }
    c.output().expect("run ckpt")
}

fn json_of(args: &[&str]) -> serde_json::Value {
    serde_json::from_str(&ok(args)).unwrap()
}

/// Real megatron-core TP2/PP2 checkpoints (scripts/make_megatron_fixtures.py --tiny).
#[test]
fn megatron_legacy_and_torch_dist() {
    let j = json_of(&["inspect", "--json", s(&fix("megatron/legacy"))]);
    assert_eq!(j["format"], "megatron-legacy");
    assert_eq!(j["info"]["tensor_parallel"], 2);
    assert_eq!(j["info"]["pipeline_parallel"], 2);
    let j = json_of(&["inspect", "--json", s(&fix("megatron/torch_dist"))]);
    assert_eq!(j["format"], "megatron-torch-dist");
    // TP/PP merge is bit-exact vs megatron-core's own TP=1 gather
    let d = ok(&[
        "diff",
        s(&fix("megatron/legacy")),
        s(&fix("megatron/reference/model.safetensors")),
    ]);
    assert!(d.contains("RESULT: EQUAL"), "{d}");
    // both formats convert to the same HF Qwen2 checkpoint
    let td = tempfile::tempdir().unwrap();
    let (a, b) = (td.path().join("a"), td.path().join("b"));
    ok(&["convert", s(&fix("megatron/legacy")), "-o", s(&a)]);
    ok(&["convert", s(&fix("megatron/torch_dist")), "-o", s(&b)]);
    assert!(ok(&["diff", s(&a), s(&b)]).contains("RESULT: EQUAL"));
    let cfg: serde_json::Value =
        serde_json::from_slice(&std::fs::read(a.join("config.json")).unwrap()).unwrap();
    assert_eq!(cfg["architectures"][0], "Qwen2ForCausalLM");
    assert_eq!(cfg["vocab_size"], 50);
    let h = json_of(&["inspect", "--json", s(&a)]);
    let t: std::collections::HashMap<String, serde_json::Value> = h["tensors"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| (x["name"].as_str().unwrap().to_string(), x.clone()))
        .collect();
    assert_eq!(
        t["model.embed_tokens.weight"]["shape"],
        serde_json::json!([50, 16])
    ); // unpadded
    assert_eq!(
        t["model.layers.1.self_attn.k_proj.weight"]["shape"],
        serde_json::json!([8, 16])
    );
    // GQA tensor-parallel round trip on the converted model (kv heads 2, tp 4 -> kv replication)
    let rules = Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/llama_tp_rules.yaml");
    let tp4 = td.path().join("tp4");
    ok(&[
        "reshard",
        s(&a),
        "--tp",
        "4",
        "--rules",
        s(&rules),
        "-o",
        s(&tp4),
    ]);
    let m = td.path().join("m.safetensors");
    ok(&["reshard", s(&tp4), "-o", s(&m)]);
    assert!(ok(&["diff", s(&m), s(&a)]).contains("RESULT: EQUAL"));
}

/// Real DeepSpeed ZeRO-2/3 checkpoints (3 ranks) vs DeepSpeed's own zero_to_fp32 output.
#[test]
fn deepspeed_zero_reconstruction() {
    for st in ["zero2", "zero3"] {
        let d = ok(&[
            "diff",
            s(&fix(&format!("deepspeed/{st}"))),
            s(&fix(&format!("deepspeed/{st}/reference.safetensors"))),
        ]);
        assert!(d.contains("RESULT: EQUAL"), "{st}: {d}");
    }
}

#[test]
fn dtype_conversion() {
    let td = tempfile::tempdir().unwrap();
    let out = td.path().join("bf16.safetensors");
    ok(&[
        "convert",
        s(&fix("reference/model.safetensors")),
        "-o",
        s(&out),
        "--dtype",
        "bf16",
    ]);
    let j = json_of(&["inspect", "--json", s(&out)]);
    assert_eq!(j["params_by_dtype"]["BF16"], j["total_params"]);
    // bf16 keeps ~3 significant digits
    let d = ckpt(&[
        "diff",
        s(&out),
        s(&fix("reference/model.safetensors")),
        "--json",
    ]);
    let r: serde_json::Value = serde_json::from_slice(&d.stdout).unwrap();
    for t in r["tensors"].as_array().unwrap() {
        assert!(t["rel_l2"].as_f64().unwrap() < 4e-3, "{t}");
    }
    let bad = ckpt(&[
        "convert",
        s(&fix("reference/model.safetensors")),
        "-o",
        s(&out),
        "--dtype",
        "int4",
    ]);
    assert_eq!(bad.status.code(), Some(2));
}

#[test]
fn verify_crc_and_forced_zip64() {
    let td = tempfile::tempdir().unwrap();
    // zip64 records (forced on small chunks) read back by our reader with CRC checks
    let dcp = td.path().join("dcp64");
    let o = ckpt_env(
        &[
            "convert",
            s(&fix("reference/model.safetensors")),
            "--to",
            "dcp",
            "--dcp-ranks",
            "2",
            "-o",
            s(&dcp),
        ],
        &[("CKPT_FORCE_ZIP64", "1")],
    );
    assert!(o.status.success(), "{}", String::from_utf8_lossy(&o.stderr));
    let d = ok(&[
        "--verify",
        "diff",
        s(&dcp),
        s(&fix("reference/model.safetensors")),
    ]);
    assert!(d.contains("RESULT: EQUAL"));
    // corrupt one byte of tensor data in a torch_save chunk
    let bad = td.path().join("bad");
    std::fs::create_dir(&bad).unwrap();
    for e in std::fs::read_dir(fix("dcp_fsdp")).unwrap() {
        let p = e.unwrap().path();
        std::fs::copy(&p, bad.join(p.file_name().unwrap())).unwrap();
    }
    // middle of the largest chunk = inside its tensor data entry
    let j = json_of(&["inspect", "--json", "--chunks", s(&bad)]);
    let c = j["tensors"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|t| t["chunks"].as_array().unwrap().clone())
        .max_by_key(|c| c["length"].as_u64().unwrap())
        .unwrap();
    let f = bad.join(c["file"].as_str().unwrap());
    let mut b = std::fs::read(&f).unwrap();
    let pos = (c["offset"].as_u64().unwrap() + c["length"].as_u64().unwrap() / 2) as usize;
    b[pos] ^= 0x10;
    std::fs::write(&f, &b).unwrap();
    assert!(
        ckpt(&[
            "convert",
            s(&bad),
            "-o",
            s(&td.path().join("x.safetensors"))
        ])
        .status
        .success()
    );
    let o = ckpt(&[
        "--verify",
        "convert",
        s(&bad),
        "-o",
        s(&td.path().join("y.safetensors")),
    ]);
    assert_eq!(o.status.code(), Some(2));
    let o = ckpt(&["inspect", "--verify", "--summary", s(&bad)]);
    assert_eq!(o.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&o.stderr).contains("CRC32 mismatch"));
    assert!(ok(&["inspect", "--verify", "--summary", s(&fix("dcp_fsdp"))]).contains("CRC32 OK"));
}
